<?php
session_start(); 
header("Cache-control: private"); //IE 6 Fix 
//include '_private/db1.php';
//include '_private/constants.php';
//include 'login.php';
include 'header.php';

echo '<head><link rel="stylesheet" href="style.css" type="text/css" /><meta http-equiv="content-type" content="text-html; charset=utf-8"></head>';
echo '<title>recruitment</title>';

// CONSTANTS
$lang = $_GET[lang];

//************* MAIN TEXT *************
// THIS TEXT IS BILINGUAL: DO NOT PERFORM LANGUAGE CHECK
echo '<div id="main">';
	echo '<h3 align=center>RECRUTEMENT / RECRUITMENT</h3>';
?>
	<ul>
		<li><a href="#schedule">Recruitment Schedule & Application Requirements</a></li>
	</ul>

		<p>The <b>McGill Health Law Publication</b> (MHLP) is a cutting edge initiative founded and led by students at McGill University's Faculty of Law. With three primary components: (1) a peer-reviewed academic publication project, (2) a website and on-line community, and (3) educational workshops and panels hosted at the Faculty, the MHLP provides a wealth of opportunities for student involvement in the exciting and growing area of health law.
		<p>With the launch of the <b>MHLP publication project</b> expected early in 2007, there are opportunities for first and upper-year students to join our editorial and management teams for the 2006-07 academic year. Ce projet multidisciplinaire compte plusieurs contributions de chercheurs et de praticiens renomm&#233s en droit de la sant&#233, r&#233vis&#233es par un comit&#233 de lecture.
		<p>The <b>MHLP website</b> marks a new approach to student contribution, with an evolving research database on various topics in health law generated by our student members. In the fall of 2006, our student web team will create a new virtual discussion space for students, faculty, and community members. Le MHLP va ainsi ouvrir la voie &#224 une nouvelle mani&#232re d'apprendre, de partager les id&#233es et de cr&#233er des contacts entre les &#233tudiants et la communaut&#233 en g&#233n&#233ral. 
		<p>Since <b>workshops, conferences, and discussion panels</b> create exciting learning environments and an opportunity to join forces with faculty members, the MHLP offers at least one event of this kind per academic year. L'organisation de ces &#233v&#233nements est une exp&#233rience enrichissante pour notre &#233quipe d’&#233tudiants et une excellente fa&#231on de contribuer &#224 la vie de la facult&#233.
		<p>The MHLP has the following <b>positions available for 2006/2007</b>:
<ol><li type=i>English Executive Editors (2), one in charge of internal editorial 
team and one in charge of external communications and relations;
	<li type=i>French Executive Editor (1);
	<li type=i>Executive Managing Editor (1);
	<li type=i>English and French Associate Editors;
	<li type=i>Managing Editors;
	<li type=i>Web and layout editors;
	<li type=i>Grant Writer / Fundraiser / Treasurer;
	<li type=i>Event Planner.
</ol>

<BR><BR>
		<a name=schedule><h4>Recruitment Schedule</h4></a>
<BLOCKQUOTE>*Please check back on this site for date, time, or location changes</BLOCKQUOTE>

<p><TABLE BORDER="0" cellspacing="10" width="600">
	<TR><TH>Event</TH><TH>Date</TH><TH>Time</TH><TH>Location</TH></TR>
	<TR><TD class="body">Campus Tour</TD>
		<TD class="body">Tuesday, September 5</TD>
		<TD class="body">14:30 - 16:00</TD>
		<TD class="body">3661 Peel</TD>
	</TR>
	<TR><TD class="body">Clubs Day</TD>
		<TD class="body">Wednesday, September 13</TD>
		<TD class="body">12:30 - 14:30</TD>
		<TD class="body">Atrium</TD>
	</TR>
	<TR><TD class="body">First MHLP Meeting</TD>
		<TD class="body">Monday, September 18</TD>
		<TD class="body">13:30 - 14:30</TD>
		<TD class="body">Room 202, NCDH</TD>
	</TR>
	<TR><TD class="body"><b>*Applications Due*</b></TD>
		<TD class="body">Monday, October 2</TD>
		<TD class="body">17:00</TD>
		<TD class="body">MHLP Mailbox<BR>3661 Peel Street</TD>
	</TR>
	<TR><TD class="body">Interviews</TD>
		<TD class="body">Tuesday, October 3 - <BR>Tuesday, October 10</TD>
		<TD class="body">Various</TD>
		<TD class="body">Various</TD>
	</TR>
	<TR><TD class="body">MHLP Team Announced</TD>
		<TD class="body">Monday, October 16</TD>
		<TD class="body">N/A</TD>
		<TD class="body">N/A</TD>
	</TR>
</TABLE>


<BR><BR>
<h4>Application Requirements</h4>
<BR>
<p>To apply for a position with the MHLP, please attend the first meeting of the MHLP on Monday, September 18, 2006 from 13:00 until 14:00 in Room 203 NCDH. This meeting will provide a wealth of information about MHLP's past and future, as well as the positions available and the application process. 

<p>By Monday, October 2, 2006 at 17:00, please submit an application to the MHLP mailbox located at 3661 Peel (our mailbox is labeled "Health Law Pub"). 

<p>Applications should include:

<ol>
	<li>250-500 word letter stating why you are interested in the MHLP, what you feel you will be able to contribute to the team, and what position you are interested in and why. This letter will be considered a writing sample.
	</li>
	<li>Curriculum Vitae (Maximum 2 pages)
	</li>
</ol>

<p>If you have any questions regarding the application process or requirements, please contact our Executive Managing Editor, Gillian Nycum at <a href="mailto:gillian.nycum@mail.mcgill.ca">gillian.nycum@mail.mcgill.ca</a>.


<?php
echo '</div>';

?>