<?
include("includes/lang_test.inc.php");
?><div class="header3" style="margin-bottom:-8px; float:left"><?=$res_title[$sess->lang][2]?></div>
<div style="float:right; padding:5px; margin-bottom:5px;">
<b><a href="documents/MHLP Forum Procedure <?=$sess->lang?>.pdf"><?=$misc_text['download'][$sess->lang]?></a></b>
</div>
<br clear="all" />
<p>1. Each  Forum article submitted first undergoes an internal review process by MJLH  editors. This process normally takes three weeks, but may take longer. The  Forum article will be evaluated based on the interpretation of the article  commented upon, originality, argumentation, clarity of thesis, quality of  language, correctness of references to past scholarship, and importance of the  article to the field. Upon the completion of this step, author(s) will be  informed of whether their Forum submission has been accepted for peer review. </p>
<p>2. Selected  Forum articles are sent to two peer reviewers, who are chosen based on the fit  between their area(s) of expertise and the subject matter of the commentary.  This process normally takes three (3) weeks, but may take significantly longer  depending upon the availability of peer reviewers. The MJLH operates on a  double-blind peer review model. </p>
<p>3. The  entire editorial review process for each Forum article may take as little as  six (6) but up to fifteen (15) weeks or more to be completed. Please note that  Forum articles received during the summer months (May through August,  inclusive) may be subject to longer editorial timeframes.</p>
<p>4. Upon  completion of the editorial process, commentators will be informed of whether  their Forum submission is (a) accepted as is, (b) conditionally accepted,  subject to certain changes being made by the author(s), or (c) not accepted.  Authors will be sent the comments of both peer reviewers. </p>
<p>5. If the  Forum article is accepted for publication, a copyright agreement will be mailed  or emailed to the author for signature. Once the final modifications are made  to the text, the author will send the MJLH a signed copyright agreement along  with a final version of the article in publishable form. Authors retain  copyright in their articles but grant the MJLH an irrevocable, royalty-free,  exclusive license, lasting for the duration equal to the author’s copyright in  the article, to publish the authors article for the first time. Articles  published in the MJLH may subsequently be reproduced or re-published, in whole  or in part, in other journals, provided that the article or a portion of it, as  the case may be, is clearly marked as originating in the MJLH.</p>
<p>6. While  Forum commentaries may be published in hard-copy format, they may only be  published online at <u>www.mjlh.mcgill.ca</u>. </p>
