<?
include("includes/lang_test.inc.php");
?><div class="header3" style="margin-bottom:-8px;">Reproductive Technologies</div>

<p>The <A href="http://laws.justice.gc.ca/en/A-13.4/">Assisted Human   Reproduction Act [Not in force] S.C. 2004, c. 2</A> prohibits assisted   reproduction procedures that are considered to be ethically unacceptable. Other   types of assisted reproduction procedures are prohibited unless carried out in   accordance with a licence and applicable regulations, which will address health   and safety concerns. The creation and use of embryos for research purposes is   also addressed. A privacy regime governs the collection, use and disclosure of   health reporting information.   
<p>History   
<UL>
  <LI>In 1989, the federal government created the Royal Commission on Reproductive   Technologies, in response to growing public concerns. The Royal Commission made   293 recommendations, concluding that decisive, timely, and comprehensive   national action was required with respect to the regulation of new reproductive   technologies. The Royal Commission stated that the federal government should use   its power under the Criminal Code and prohibit certain practices. <BR>
    Royal   Commission, Proceed With Care: Final Report of the Royal Commission on New   Reproductive Technologies (Ottawa: Minister of Supply and Services Canada,   1993).   
  <LI>In 1996, the federal government introduced Bill C-47, which included a list   of prohibited activities and imposed criminal sanctions for infringements of   serious prohibitions. See <A href="http://www.parl.gc.ca/PDF/35/2/parlbus/chambus/house/bills/government/C-47_1.pdf">An   Act Respecting Human Reproductive Technologies and Commercial Transactions   relating to Human reproduction</A> (PDF)   
  <LI>In 1997, the Canadian Bar Association responded to Bill C-47 by strongly   criticizing the use of criminal prohibitions for failing to balance "individual   autonomy" and the inherent dangers in the use of reproductive technology. The   CBA was also concerned with the possible "chilling effect" on research and   clinical practice. It recommended professional self-regulation. Other   commentators recommended a regulatory rather than a criminal framework to avoid   pushing reproductive technologies practices to the underground market.   
  <LI>At the same time, the federal government published a White Paper promising   to establish a regulatory framework within which the regulation of acceptable   practices would take place. The regime would provide a separate body removed   from the government, which would issue licences as well as establish standards   and information registries and health surveillance procedures. See <A href="http://www.hc-sc.gc.ca/ahc-asc/media/nr-cp/1996/1996_44_e.html">New   Reproductive Technologies: Setting Boundaries, Enhancing Health</A> (Ottawa:   Supply and Services Canada, 1996) </LI>
</UL>
<p>The <EM>Assisted Human Reproduction Act</EM> combines all three approaches:   prohibited activities, controlled activities, and the creation of a regulatory   agency. <A href="http://canadagazette.gc.ca/partII/2005/20050518/html/si42-e.html">Order   Fixing January 12, 2006 as the Date of the Coming into Force of Certain Sections   of the Act</A> </p>.
